### PR TITLE
Bottom navigation problem fixed

### PR DESCRIPTION
**Pull request by nurettinabaci**
Issue #1

### CODE REVIEW

**Comment by AhmadTakkoush** [comment]
@nurettinabaci THANK YOU! 
I still have a problem with the home navigation, i can't seem to figure out how to navigate back to home after profile or explore. any idea on how to approach this?

**Comment by nurettinabaci** [comment]
actually explore and profile fragments are embedded inside

**Comment by AhmadTakkoush** [comment]
so I'll just make a home fragment that has the content and embed it like the others and keep the home_page as a welcome page? is this a good approach?

**Comment by nurettinabaci** [comment]
Oh, you have already HomeFragment, I did not see that yesterday. let me fix that.

**Comment by AhmadTakkoush** [comment]
so I'll just make a home fragment that has the content and embed it like the others and keep the home_page as a welcome page?

**Comment by nurettinabaci** [comment]
It seems you handled it. 

```
case R.id.nav_profile:
                        mSelectedFragment = new ProfileFragment();
                        // add break; here

                    default:
```

**Comment by AhmadTakkoush** [comment]
yes, thank you again for the help aprreaciate it

**Pull request merged**
